"""empty message

Revision ID: 25d77ee74059
Revises: f72946408e51
Create Date: 2024-03-02 21:46:20.009371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d77ee74059'
down_revision = 'f72946408e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=15), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
